// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAppForSQLPart.Models;

#nullable disable

namespace TestAppForSQLPart.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TestAppForSQLPart.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Intel"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AMD"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Baikal"
                        },
                        new
                        {
                            Id = 4,
                            Name = "New"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Used"
                        });
                });

            modelBuilder.Entity("TestAppForSQLPart.Models.Enrollment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Enrollment", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 5,
                            ProductId = 1
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            ProductId = 2
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 5,
                            ProductId = 4
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 2,
                            ProductId = 5
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            ProductId = 5
                        });
                });

            modelBuilder.Entity("TestAppForSQLPart.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Product", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Core I5 10400f",
                            Price = 100m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Core I7 11600",
                            Price = 250m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Elbrus 16SV",
                            Price = 350m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Ryzen 5 5600X zen3",
                            Price = 100m
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ryzen 5 7600X zen4",
                            Price = 300m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
